HWIO_REGISTER_FILES = [
  { u'filename': u'icbcfg_hwio.h',
    u'header': u'#include "../../../Include/msmhwiobase.h"',
    u'module-filter-exclude': { },
    u'module-filter-include': { u'GEM_NOC':         [ u'SNOOP',
                                                     u'DYNATTR',
                                                     u'PAYLOAD_RED',
                                                     u'POC_CTL',
                                                     u'POC_DBG',
                                                     u'QOSGEN',
                                                     u'RCG',
                                                     u'SBM'],
                                u'A1NOC_SERVICE_NETWORK ': [u'RCG'],
                                u'A2NOC_SERVICE_NETWORK': [u'RCG'],
                                u'PCIE_ANOC_SERVICE_NETWORK': [u'RCG'],
                                u'CNOC_CFG_SERVICE_NETWORK': [u'RCG'],
                                u'SNOC_SERVICE_NETWORK': [u'RCG'],
                                u'MCCC_MCCC_MSTR': [ u'PERIOD'],
                                u'GCC_CLK_CTL_REG': [ u'QM',
                                                      u'CBCR',
                                                      u'MMNOC_GDSCR' ],
                                u'MMSS_NOC_SF': [ u'CAMNOC.*?DYN', u'RCG', u'GDSCR'],
                                u'MMSS_NOC_HF': [ u'CAMNOC.*?DYN', u'RCG', u'GDSCR'],
                                u'QTB_NOC_LPASS': [u'RCG'],
                                u'QTB_NOC_NSP': [u'RCG'],
                                u'TURING_NSP_NOC': [u'RCG'],
                                u'CNOC_MAIN_SERVICE_NETWORK': [ u'GEMNOC_DYNATTR', u'RCG', u'CSRUNIT' ],
                                u'LPASS_AG_NOC':    [ u'DYN' ],
                                u'MC_BROADCAST_ANDMC_COMMON_ISU' : [u'LOCK'],
                                u'MC_BROADCAST_ORMC_COMMON_ISU' : [u'ISU_LOAD_CONFIG']},
    u'modules': [ u'QM',
                  u'APP_BWMON_THROTTLE_0_THROTTLE_0_THROTTLE',
                  u'APP_BWMON_THROTTLE_1_THROTTLE_1_THROTTLE',
                  u'GPU_BWMON_THROTTLE_0_THROTTLE_0_THROTTLE',
                  u'GPU_BWMON_THROTTLE_1_THROTTLE_1_THROTTLE',
                  u'CDSP_BWMON_THROTTLE_0_THROTTLE_0_THROTTLE',
                  u'CDSP_BWMON_THROTTLE_1_THROTTLE_1_THROTTLE',
                  u'PCIE_THROTTLE_THROTTLE_0_THROTTLE_0_THROTTLE',
                  u'SNOC_THROTTLE_THROTTLE_0_THROTTLE_0_THROTTLE',
                  u'GPU_TCU_THROTTLE_THROTTLE_0_THROTTLE_0_THROTTLE',
                  u'ANOC1_THROTTLE_THROTTLE_0_THROTTLE_0_THROTTLE',
                  u'ANOC2_THROTTLE_THROTTLE_0_THROTTLE_0_THROTTLE',
                  u'LPASS_THROTTLE_THROTTLE_0_THROTTLE_0_THROTTLE',
                  u'MODEM_DSP_THROTTLE_THROTTLE_0_THROTTLE_0_THROTTLE',
                  u'GEM_NOC',
                  u'A1NOC_SERVICE_NETWORK',
                  u'A2NOC_SERVICE_NETWORK',
                  u'PCIE_ANOC_SERVICE_NETWORK',
                  u'CNOC_CFG_SERVICE_NETWORK',
                  u'SNOC_SERVICE_NETWORK',
                  u'MCCC_MCCC_MSTR',
                  u'GCC_CLK_CTL_REG',
                  u'MMSS_NOC_SF',
                  u'MMSS_NOC_HF',
                  u'TURING_NSP_NOC',
                  u'QTB_NOC_LPASS',
                  u'QTB_NOC_NSP',
                  u'CNOC_MAIN_SERVICE_NETWORK',
                  u'LPASS_AG_NOC',
                  u'MC_BROADCAST_ANDMC_COMMON_ISU',
                  u'MC_BROADCAST_ORMC_COMMON_ISU']},
  { u'filename': u'icbcfg_hwio_target.h',
    u'header': u'#include "../../Include/msmhwiobase.h"',
    u'module-filter-exclude': { },
    u'module-filter-include': { u'MC0_MC_COMMON_ISU': [u'ADDR_TRANSLATOR_CFG'],
                                u'MC1_MC_COMMON_ISU': [u'ADDR_TRANSLATOR_CFG']},
    u'modules': [u'MC0_MC_COMMON_ISU',
                 u'MC1_MC_COMMON_ISU']},
]

if __name__ == "__main__":
  import sys, os
  from subprocess import call

  flat_path = '../../../Tools/hwio/ARM_ADDRESS_FILE_SW.FLAT'
  if os.name == 'nt':
    hwio_path = r'C:\hwio_gen\HWIOGen.py'
  else:
    hwio_path = r'/prj/qct/corebsp_labdata_0001/sysdrv/hwio/legacy/HWIOGen.py'

  call(['python', hwio_path, '--cfg', __file__, '--flat', flat_path] + sys.argv[1:])
