HWIO_REGISTER_FILES = [
  { u'filename': u'icbcfg_hwio.h',
    u'header': u'#include "../../../Include/msmhwiobase.h"',
    u'module-filter-exclude': { },
    u'module-filter-include': { u'GEM_NOC':         [ u'SNOOP',
                                                     u'DYNATTR',
                                                     u'PAYLOAD_RED',
                                                     u'POC_CTL',
                                                     u'POC_DBG',
                                                     u'QOSGEN',
                                                     u'RCG',
                                                     u'SBM'],
                                u'A1_NOC_A1NOC_SERVICE_NETWORK': [u'RCG'],
                                u'A2_NOC_A2NOC_SERVICE_NETWORK': [u'RCG'],
                                u'PCIE_ANOC_SERVICE_NETWORK': [u'RCG'],
                                u'CNOC_CFG_SERVICE_NETWORK': [u'RCG'],
                                u'SNOC_SERVICE_NETWORK': [u'RCG'],
                                u'MCCC_MCCC_MSTR': [ u'PERIOD'],
                                u'GCC_CLK_CTL_REG': [ u'QM',
                                                      u'CBCR',
                                                      u'MMNOC_GDSCR' ],
                                u'MMSS_NOC':        [ u'CAMNOC.*?DYN', u'RCG', u'GDSCR'],
                                u'QTB_NOC_LPASS': [u'RCG'],
                                u'QTB_NOC_NSP': [u'RCG'],
                                u'TURING_NSP_NOC': [u'RCG'],
                                u'CNOC_MAIN_SERVICE_NETWORK': [ u'GEMNOC_DYNATTR', u'RCG', u'CSRUNIT' ],
                                u'LPASS_AG_NOC':    [ u'DYN' ],
                                u'LLCC_BROADCAST_ANDFEAC': [ u'TCM', u'VICTIM' ],
                                u'LLCC_BROADCAST_ORFEAC': [ u'TCM', u'VICTIM' ],
                                u'LLCC_BROADCAST_ANDLLCC_BEAC0': [ u'LOCK' ],
                                u'LLCC_BROADCAST_ORLLCC_BEAC0': [ u'LOCK' ],
                                u'LLCC_BROADCAST_ANDTRP': [ u'OVERRIDE', u'CFLUSH', u'ALGO', u'ATTRIBUTE' ],
                                u'LLCC_BROADCAST_ORTRP': [ u'OVERRIDE', u'CFLUSH', u'ALGO', u'ATTRIBUTE' ]},
    u'modules': [ u'QM',
                  u'APP_BWMON_THROTTLE_0_THROTTLE_0_THROTTLE',
                  u'APP_BWMON_THROTTLE_1_THROTTLE_1_THROTTLE',
                  u'GPU_BWMON_THROTTLE_0_THROTTLE_0_THROTTLE',
                  u'GPU_BWMON_THROTTLE_1_THROTTLE_1_THROTTLE',
                  u'CDSP_BWMON_THROTTLE_0_THROTTLE_0_THROTTLE',
                  u'CDSP_BWMON_THROTTLE_1_THROTTLE_1_THROTTLE',
                  u'PCIE_THROTTLE_THROTTLE_0_THROTTLE_0_THROTTLE',
                  u'SNOC_THROTTLE_THROTTLE_0_THROTTLE_0_THROTTLE',
                  u'GPU_TCU_THROTTLE_THROTTLE_0_THROTTLE_0_THROTTLE',
                  u'ANOC1_THROTTLE_THROTTLE_0_THROTTLE_0_THROTTLE',
                  u'ANOC2_THROTTLE_THROTTLE_0_THROTTLE_0_THROTTLE',
                  u'LPASS_THROTTLE_THROTTLE_0_THROTTLE_0_THROTTLE',
                  u'MODEM_DSP_THROTTLE_THROTTLE_0_THROTTLE_0_THROTTLE',
                  u'GIC_THROTTLE_THROTTLE_0_THROTTLE_0_THROTTLE',
                  u'UBWC_QNS_BWMON_THROTTLE_0_THROTTLE_0_THROTTLE',
                  u'UBWC_AXI_BWMON_THROTTLE_0_THROTTLE_0_THROTTLE',
                  u'GEM_NOC',
                  u'A1_NOC_A1NOC_SERVICE_NETWORK',
                  u'A2_NOC_A2NOC_SERVICE_NETWORK',
                  u'PCIE_ANOC_SERVICE_NETWORK',
                  u'CNOC_CFG_SERVICE_NETWORK',
                  u'SNOC_SERVICE_NETWORK',
                  u'MCCC_MCCC_MSTR',
                  u'GCC_CLK_CTL_REG',
                  u'MMSS_NOC',
                  u'TURING_NSP_NOC',
                  u'QTB_NOC_LPASS',
                  u'QTB_NOC_NSP',
                  u'CNOC_MAIN_SERVICE_NETWORK',
                  u'LPASS_AG_NOC',
                  u'LLCC_BROADCAST_ORLPI_SHARED',
                  u'LLCC_BROADCAST_ANDTRP',
                  u'LLCC_BROADCAST_ORTRP',
                  u'LLCC_BROADCAST_ANDFEAC',
                  u'LLCC_BROADCAST_ORFEAC',
                  u'LLCC_BROADCAST_ANDLLCC_BEAC0',
                  u'LLCC_BROADCAST_ORLLCC_BEAC0' ]},
  { u'filename': u'icbcfg_hwio_target.h',
    u'header': u'#include "../../Include/msmhwiobase.h"',
    u'module-filter-exclude': { },
    u'module-filter-include': { u'LLCC0_LLCC_BEAC0': [u'ADDR_TRANSLATOR_CFG'],
                                u'LLCC1_LLCC_BEAC0': [u'ADDR_TRANSLATOR_CFG'],
                                u'LLCC2_LLCC_BEAC0': [u'ADDR_TRANSLATOR_CFG'],
                                u'LLCC3_LLCC_BEAC0': [u'ADDR_TRANSLATOR_CFG']},
    u'modules': [u'LLCC0_LLCC_BEAC0',
                 u'LLCC1_LLCC_BEAC0',
                 u'LLCC2_LLCC_BEAC0',
                 u'LLCC3_LLCC_BEAC0']},
]

if __name__ == "__main__":
  import sys, os
  from subprocess import call

  flat_path = '../../../Tools/hwio/ARM_ADDRESS_FILE.FLAT'
  if os.name == 'nt':
    hwio_path = r'\\ben\corebsp_labdata_0001\sysdrv\hwio\legacy\HWIOGen.py'
  else:
    hwio_path = r'/prj/qct/corebsp_labdata_0001/sysdrv/hwio/legacy/HWIOGen.py'

  call(['python', hwio_path, '--cfg', __file__, '--flat', flat_path] + sys.argv[1:])
