#ifndef __I2C_DEFINES_H__
#define __I2C_DEFINES_H__


/*=============================================================================   
    @file  i2c_config.h
    @brief interface to device configuration
   
    Copyright (c) 2022 Qualcomm Technologies, Incorporated.
                        All rights reserved.
    Qualcomm Technologies, Confidential and Proprietary.
===============================================================================*/

/*=============================================================================
                              EDIT HISTORY
 when       who     what, where, why
 --------   ---     -----------------------------------------------------------
 06/01/22   gkr     Added Strongpull Support
 09/20/22   ag      Added file for Lanai
=============================================================================*/

// NOTE: QUPs are numbered starting from 0 as per the IO sheet
#define ENABLE_QUP_01
#define ENABLE_QUP_10
#define ENABLE_QUP_13
#define ENABLE_QUP_16

// I2C_MASTER_0 [se0 - se9] [0:9]
#define QUPV3_0_CORE_BASE_ADDRESS        0x00900000
#define QUPV3_0_CORE_COMMON_BASE_ADDRESS 0x009C0000

// QUPV3_1 [se0 - se7] [10:17]
#define QUPV3_1_CORE_BASE_ADDRESS        0x00A00000
#define QUPV3_1_CORE_COMMON_BASE_ADDRESS 0x00AC0000

// QUPV3_2 [se0 - se7] [18:25]
#define QUPV3_2_CORE_BASE_ADDRESS        0x00800000
#define QUPV3_2_CORE_COMMON_BASE_ADDRESS 0x008C0000

#define TLMM_GPIO_CFG_EX(gpio, func, dir, pull, drive, strongpull) \
                                      (((gpio) & 0x3FF) << 4  | \
                                       ((func) & 0xF  ) << 0  | \
                                       ((dir)  & 0x1  ) << 14 | \
                                       ((pull) & 0x3  ) << 15 | \
                                       ((drive)& 0xF  ) << 17 | \
                                       ((strongpull)& 0x1) << 30)

#define TLMM_GPIO_INPUT             0x0
#define TLMM_GPIO_NO_PULL           0x0
#define TLMM_GPIO_PULL_UP           0x3
#define TLMM_GPIO_2MA               0x0
#define TLMM_GPIO_STRONG_PULL       0x1
#define TLMM_GPIO_NO_STRONG_PULL    0x0

#define QUP_0   0
#define QUP_1   1
#define QUP_2   2

//
// CONFIGURATION START ============================================
//
#define TOP_QUP_00_SDA TLMM_GPIO_CFG_EX(64 , 1, TLMM_GPIO_INPUT, TLMM_GPIO_PULL_UP, TLMM_GPIO_2MA, TLMM_GPIO_STRONG_PULL)
#define TOP_QUP_00_SCL TLMM_GPIO_CFG_EX(65 , 1, TLMM_GPIO_INPUT, TLMM_GPIO_PULL_UP, TLMM_GPIO_2MA, TLMM_GPIO_STRONG_PULL)
                                    
#define TOP_QUP_01_SDA TLMM_GPIO_CFG_EX(66 , 1, TLMM_GPIO_INPUT, TLMM_GPIO_NO_PULL, TLMM_GPIO_2MA, TLMM_GPIO_STRONG_PULL)
#define TOP_QUP_01_SCL TLMM_GPIO_CFG_EX(67 , 1, TLMM_GPIO_INPUT, TLMM_GPIO_NO_PULL, TLMM_GPIO_2MA, TLMM_GPIO_STRONG_PULL)
                                    
#define TOP_QUP_02_SDA TLMM_GPIO_CFG_EX(68 , 1, TLMM_GPIO_INPUT, TLMM_GPIO_PULL_UP, TLMM_GPIO_2MA, TLMM_GPIO_STRONG_PULL)
#define TOP_QUP_02_SCL TLMM_GPIO_CFG_EX(69 , 1, TLMM_GPIO_INPUT, TLMM_GPIO_PULL_UP, TLMM_GPIO_2MA, TLMM_GPIO_STRONG_PULL)
                                    
#define TOP_QUP_03_SDA TLMM_GPIO_CFG_EX(70 , 1, TLMM_GPIO_INPUT, TLMM_GPIO_PULL_UP, TLMM_GPIO_2MA, TLMM_GPIO_STRONG_PULL)
#define TOP_QUP_03_SCL TLMM_GPIO_CFG_EX(71 , 1, TLMM_GPIO_INPUT, TLMM_GPIO_PULL_UP, TLMM_GPIO_2MA, TLMM_GPIO_STRONG_PULL)
                                    
#define TOP_QUP_04_SDA TLMM_GPIO_CFG_EX(72 , 1, TLMM_GPIO_INPUT, TLMM_GPIO_PULL_UP, TLMM_GPIO_2MA, TLMM_GPIO_STRONG_PULL)
#define TOP_QUP_04_SCL TLMM_GPIO_CFG_EX(73 , 1, TLMM_GPIO_INPUT, TLMM_GPIO_PULL_UP, TLMM_GPIO_2MA, TLMM_GPIO_STRONG_PULL)
                                    
#define TOP_QUP_05_SDA TLMM_GPIO_CFG_EX(74 , 1, TLMM_GPIO_INPUT, TLMM_GPIO_PULL_UP, TLMM_GPIO_2MA, TLMM_GPIO_STRONG_PULL)
#define TOP_QUP_05_SCL TLMM_GPIO_CFG_EX(75 , 1, TLMM_GPIO_INPUT, TLMM_GPIO_PULL_UP, TLMM_GPIO_2MA, TLMM_GPIO_STRONG_PULL)
                                    
#define TOP_QUP_06_SDA TLMM_GPIO_CFG_EX(76 , 1, TLMM_GPIO_INPUT, TLMM_GPIO_PULL_UP, TLMM_GPIO_2MA, TLMM_GPIO_STRONG_PULL)
#define TOP_QUP_06_SCL TLMM_GPIO_CFG_EX(77 , 1, TLMM_GPIO_INPUT, TLMM_GPIO_PULL_UP, TLMM_GPIO_2MA, TLMM_GPIO_STRONG_PULL)
                                    
#define TOP_QUP_07_SDA TLMM_GPIO_CFG_EX(78 , 1, TLMM_GPIO_INPUT, TLMM_GPIO_PULL_UP, TLMM_GPIO_2MA, TLMM_GPIO_STRONG_PULL)
#define TOP_QUP_07_SCL TLMM_GPIO_CFG_EX(79 , 1, TLMM_GPIO_INPUT, TLMM_GPIO_PULL_UP, TLMM_GPIO_2MA, TLMM_GPIO_STRONG_PULL)
                                    
#define TOP_QUP_08_SDA TLMM_GPIO_CFG_EX(206, 1, TLMM_GPIO_INPUT, TLMM_GPIO_PULL_UP, TLMM_GPIO_2MA, TLMM_GPIO_NO_STRONG_PULL)
#define TOP_QUP_08_SCL TLMM_GPIO_CFG_EX(207, 1, TLMM_GPIO_INPUT, TLMM_GPIO_PULL_UP, TLMM_GPIO_2MA, TLMM_GPIO_NO_STRONG_PULL)
                                    
#define TOP_QUP_09_SDA TLMM_GPIO_CFG_EX(80 , 1, TLMM_GPIO_INPUT, TLMM_GPIO_PULL_UP, TLMM_GPIO_2MA, TLMM_GPIO_STRONG_PULL)
#define TOP_QUP_09_SCL TLMM_GPIO_CFG_EX(81 , 1, TLMM_GPIO_INPUT, TLMM_GPIO_PULL_UP, TLMM_GPIO_2MA, TLMM_GPIO_STRONG_PULL)
                                    
#define TOP_QUP_10_SDA TLMM_GPIO_CFG_EX(32 , 1, TLMM_GPIO_INPUT, TLMM_GPIO_PULL_UP, TLMM_GPIO_2MA, TLMM_GPIO_NO_STRONG_PULL)
#define TOP_QUP_10_SCL TLMM_GPIO_CFG_EX(33 , 1, TLMM_GPIO_INPUT, TLMM_GPIO_PULL_UP, TLMM_GPIO_2MA, TLMM_GPIO_NO_STRONG_PULL)
                                    
#define TOP_QUP_11_SDA TLMM_GPIO_CFG_EX(36 , 1, TLMM_GPIO_INPUT, TLMM_GPIO_PULL_UP, TLMM_GPIO_2MA, TLMM_GPIO_NO_STRONG_PULL)
#define TOP_QUP_11_SCL TLMM_GPIO_CFG_EX(37 , 1, TLMM_GPIO_INPUT, TLMM_GPIO_PULL_UP, TLMM_GPIO_2MA, TLMM_GPIO_NO_STRONG_PULL)
                                    
#define TOP_QUP_12_SDA TLMM_GPIO_CFG_EX(40 , 1, TLMM_GPIO_INPUT, TLMM_GPIO_PULL_UP, TLMM_GPIO_2MA, TLMM_GPIO_STRONG_PULL)
#define TOP_QUP_12_SCL TLMM_GPIO_CFG_EX(41 , 1, TLMM_GPIO_INPUT, TLMM_GPIO_PULL_UP, TLMM_GPIO_2MA, TLMM_GPIO_STRONG_PULL)
                                    
#define TOP_QUP_13_SDA TLMM_GPIO_CFG_EX(44 , 1, TLMM_GPIO_INPUT, TLMM_GPIO_PULL_UP, TLMM_GPIO_2MA, TLMM_GPIO_STRONG_PULL)
#define TOP_QUP_13_SCL TLMM_GPIO_CFG_EX(45 , 1, TLMM_GPIO_INPUT, TLMM_GPIO_PULL_UP, TLMM_GPIO_2MA, TLMM_GPIO_STRONG_PULL)
                                    
#define TOP_QUP_14_SDA TLMM_GPIO_CFG_EX(48 , 1, TLMM_GPIO_INPUT, TLMM_GPIO_PULL_UP, TLMM_GPIO_2MA, TLMM_GPIO_STRONG_PULL)
#define TOP_QUP_14_SCL TLMM_GPIO_CFG_EX(49 , 1, TLMM_GPIO_INPUT, TLMM_GPIO_PULL_UP, TLMM_GPIO_2MA, TLMM_GPIO_STRONG_PULL)
                                    
#define TOP_QUP_15_SDA TLMM_GPIO_CFG_EX(52 , 1, TLMM_GPIO_INPUT, TLMM_GPIO_PULL_UP, TLMM_GPIO_2MA, TLMM_GPIO_STRONG_PULL)
#define TOP_QUP_15_SCL TLMM_GPIO_CFG_EX(53 , 1, TLMM_GPIO_INPUT, TLMM_GPIO_PULL_UP, TLMM_GPIO_2MA, TLMM_GPIO_STRONG_PULL)
                                    
#define TOP_QUP_16_SDA TLMM_GPIO_CFG_EX(56 , 1, TLMM_GPIO_INPUT, TLMM_GPIO_PULL_UP, TLMM_GPIO_2MA, TLMM_GPIO_NO_STRONG_PULL)
#define TOP_QUP_16_SCL TLMM_GPIO_CFG_EX(57 , 1, TLMM_GPIO_INPUT, TLMM_GPIO_PULL_UP, TLMM_GPIO_2MA, TLMM_GPIO_NO_STRONG_PULL)
                                    
#define TOP_QUP_17_SDA TLMM_GPIO_CFG_EX(60 , 1, TLMM_GPIO_INPUT, TLMM_GPIO_PULL_UP, TLMM_GPIO_2MA, TLMM_GPIO_STRONG_PULL)
#define TOP_QUP_17_SCL TLMM_GPIO_CFG_EX(61 , 1, TLMM_GPIO_INPUT, TLMM_GPIO_PULL_UP, TLMM_GPIO_2MA, TLMM_GPIO_STRONG_PULL)
                                    
#define TOP_QUP_18_SDA TLMM_GPIO_CFG_EX(0 , 1, TLMM_GPIO_INPUT, TLMM_GPIO_PULL_UP, TLMM_GPIO_2MA, TLMM_GPIO_NO_STRONG_PULL)
#define TOP_QUP_18_SCL TLMM_GPIO_CFG_EX(1 , 1, TLMM_GPIO_INPUT, TLMM_GPIO_PULL_UP, TLMM_GPIO_2MA, TLMM_GPIO_NO_STRONG_PULL)
                                    
#define TOP_QUP_19_SDA TLMM_GPIO_CFG_EX(4 , 1, TLMM_GPIO_INPUT, TLMM_GPIO_PULL_UP, TLMM_GPIO_2MA, TLMM_GPIO_NO_STRONG_PULL)
#define TOP_QUP_19_SCL TLMM_GPIO_CFG_EX(5 , 1, TLMM_GPIO_INPUT, TLMM_GPIO_PULL_UP, TLMM_GPIO_2MA, TLMM_GPIO_NO_STRONG_PULL)
                                    
#define TOP_QUP_20_SDA TLMM_GPIO_CFG_EX(8 , 1, TLMM_GPIO_INPUT, TLMM_GPIO_PULL_UP, TLMM_GPIO_2MA, TLMM_GPIO_NO_STRONG_PULL)
#define TOP_QUP_20_SCL TLMM_GPIO_CFG_EX(9 , 1, TLMM_GPIO_INPUT, TLMM_GPIO_PULL_UP, TLMM_GPIO_2MA, TLMM_GPIO_NO_STRONG_PULL)
                                    
#define TOP_QUP_21_SDA TLMM_GPIO_CFG_EX(12 , 1, TLMM_GPIO_INPUT, TLMM_GPIO_PULL_UP, TLMM_GPIO_2MA, TLMM_GPIO_NO_STRONG_PULL)
#define TOP_QUP_21_SCL TLMM_GPIO_CFG_EX(13 , 1, TLMM_GPIO_INPUT, TLMM_GPIO_PULL_UP, TLMM_GPIO_2MA, TLMM_GPIO_NO_STRONG_PULL)
                                    
#define TOP_QUP_22_SDA TLMM_GPIO_CFG_EX(16 , 1, TLMM_GPIO_INPUT, TLMM_GPIO_PULL_UP, TLMM_GPIO_2MA, TLMM_GPIO_STRONG_PULL)
#define TOP_QUP_22_SCL TLMM_GPIO_CFG_EX(17 , 1, TLMM_GPIO_INPUT, TLMM_GPIO_PULL_UP, TLMM_GPIO_2MA, TLMM_GPIO_STRONG_PULL)
                                    
#define TOP_QUP_23_SDA TLMM_GPIO_CFG_EX(20 , 1, TLMM_GPIO_INPUT, TLMM_GPIO_PULL_UP, TLMM_GPIO_2MA, TLMM_GPIO_STRONG_PULL)
#define TOP_QUP_23_SCL TLMM_GPIO_CFG_EX(21 , 1, TLMM_GPIO_INPUT, TLMM_GPIO_PULL_UP, TLMM_GPIO_2MA, TLMM_GPIO_STRONG_PULL)
                                    
#define TOP_QUP_24_SDA TLMM_GPIO_CFG_EX(24 , 1, TLMM_GPIO_INPUT, TLMM_GPIO_PULL_UP, TLMM_GPIO_2MA, TLMM_GPIO_STRONG_PULL)
#define TOP_QUP_24_SCL TLMM_GPIO_CFG_EX(25 , 1, TLMM_GPIO_INPUT, TLMM_GPIO_PULL_UP, TLMM_GPIO_2MA, TLMM_GPIO_STRONG_PULL)
                                    
#define TOP_QUP_25_SDA TLMM_GPIO_CFG_EX(28 , 1, TLMM_GPIO_INPUT, TLMM_GPIO_PULL_UP, TLMM_GPIO_2MA, TLMM_GPIO_STRONG_PULL)
#define TOP_QUP_25_SCL TLMM_GPIO_CFG_EX(29 , 1, TLMM_GPIO_INPUT, TLMM_GPIO_PULL_UP, TLMM_GPIO_2MA, TLMM_GPIO_STRONG_PULL)


#endif
