/*==============================================================================

FILE:      icbcfg_data.c

DESCRIPTION: This file implements the ICB Configuration driver.

PUBLIC CLASSES:  Not Applicable

INITIALIZATION AND SEQUENCING REQUIREMENTS:  N/A

Edit History

$Header: $
$DateTime: 2022/04/04 14:42:21 $
$Author: seansw $
$Change: 36371393 $

When        Who    What, where, why
----------  ---    -----------------------------------------------------------
2023/01/09  sds    CPU SCID updates
2022/09/12  sds    LLCC v17
2022/07/20  sds    GEMNOC and DC_NOC ARCG
2022/04/05  sds    Created

                Copyright (c) 2022-2023 Qualcomm Technologies, Inc.
                             All Rights Reserved.
                          QUALCOMM Proprietary/GTDR
==============================================================================*/
#include "icbcfg_hwio.h"
#include "icbcfg_hwio_target.h"
#include "../../../../../Library/ICBLib/icbcfgi.h"

/*---------------------------------------------------------------------------*/
/*          Macro and constant definitions                                   */
/*---------------------------------------------------------------------------*/
//#define ARRAY_SIZE(arr) (sizeof(arr)/sizeof((arr)[0]))

/*============================================================================
                        DEVICE CONFIG PROPERTY DATA
============================================================================*/

/*---------------------------------------------------------------------------*/
/*          Properties data for device ID  = "icbcfg/boot"                   */
/*---------------------------------------------------------------------------*/

/* ICBcfg Boot Configuration Data*/

/*---------------------------------------------------------------------------*/
/* PALAWAN v1                                                                 */
/*---------------------------------------------------------------------------*/

/*---------------------------------------------------------------------------*/
/* Init Config Segments                                                      */
/*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*/
/* QM Config Segment                                                         */
/*---------------------------------------------------------------------------*/
icbcfg_data_type icbcfg_qm_cfg_data_palawan_v1[] =
{
  /* Enable QM core cgc */
  //ICBCFG_HWIO_DW(QM_CORE_CLK_CGC_CNTRL, 0x1),
  ICBCFG_HWIO_DW(QM_FAL10_CONFIG_CNTRL, 0x000000A0),
  
  /* Stall timers */
  //ICBCFG_HWIO_DW(QM_PRE_STALL_TIMEOUT_CNT_URG_0, 0x00000060),
  //ICBCFG_HWIO_DW(QM_PRE_STALL_TIMEOUT_CNT_URG_1, 0x00000027),
  //ICBCFG_HWIO_DW(QM_PRE_STALL_TIMEOUT_CNT_URG_2, 0x00000027),
  //ICBCFG_HWIO_DW(QM_PRE_STALL_TIMEOUT_CNT_URG_3, 0x00000027),
  //ICBCFG_HWIO_DW(QM_POST_STALL_TIMEOUT_CNT_URG_0, 0x00000060),
  //ICBCFG_HWIO_DW(QM_POST_STALL_TIMEOUT_CNT_URG_1, 0x00000027),
  //ICBCFG_HWIO_DW(QM_POST_STALL_TIMEOUT_CNT_URG_2, 0x00000027),
  //ICBCFG_HWIO_DW(QM_POST_STALL_TIMEOUT_CNT_URG_3, 0x00000027),
  //ICBCFG_HWIO_DW(QM_POST_STALL_WDW_OVERLAP_CNTL, 0x00000001),
  //ICBCFG_HWIO_DW(QM_SMMU_INV_PRE_STALL_TIMEOUT_CNT_URG_0, 0x00000780),
  //ICBCFG_HWIO_DW(QM_SMMU_INV_PRE_STALL_TIMEOUT_CNT_URG_1, 0x00000300),
  //ICBCFG_HWIO_DW(QM_SMMU_INV_PRE_STALL_TIMEOUT_CNT_URG_2, 0x00000300),
  //ICBCFG_HWIO_DW(QM_SMMU_INV_PRE_STALL_TIMEOUT_CNT_URG_3, 0x00000300),
  //ICBCFG_HWIO_DW(QM_SMMU_INV_POST_STALL_WDW_OVERLAP_CNTL, 0x00000001),

  /* SAFE client overrides */
  ICBCFG_HWIO_DW(QM_DSP_SAFE_MASK_CNTRL, 0x3),
  ICBCFG_HWIO_DW(QM_SAFE_OVERRIDE_VALUE, 0x8),
  ICBCFG_HWIO_DW(QM_SAFE_OVERRIDE_EN, 0x8),

  /* Titan RT, Modem 5G*/
  //ICBCFG_HWIO_DW(QM_CLNT_0_DANGER_AGGR_CNTRL, 0x3),
  //ICBCFG_HWIOI_DW(QM_CLNT_0_THROTTLE_LEVEL_QOS_n, 4, 0xEE000004),
  //ICBCFG_HWIOI_DW(QM_CLNT_0_THROTTLE_LEVEL_QOS_n, 6, 0xEE000006),
  ICBCFG_HWIO_DW(QM_CLNT_0_THROTTLE_LEVEL_OUTPUT_EN, 0x1),

  /* Titan Non-RT */
  ICBCFG_HWIO_DW(QM_CLNT_1_DANGER_AGGR_CNTRL, 0x3),
  ICBCFG_HWIOI_DW(QM_CLNT_1_THROTTLE_LEVEL_QOS_n, 4, 0xEE000004),
  ICBCFG_HWIOI_DW(QM_CLNT_1_THROTTLE_LEVEL_QOS_n, 6, 0xEE000006),
  ICBCFG_HWIO_DW(QM_CLNT_1_THROTTLE_LEVEL_OUTPUT_EN, 0x1),

  /* AML0 */
  ICBCFG_HWIO_DW(QM_CLNT_2_DANGER_AGGR_CNTRL, 0x3),
  ICBCFG_HWIOI_DW(QM_CLNT_2_THROTTLE_LEVEL_QOS_n, 7, 0xEE000003),
  ICBCFG_HWIO_DW(QM_CLNT_2_THROTTLE_LEVEL_OUTPUT_EN, 0x3),

  /* PCIe */
  ICBCFG_HWIO_DW(QM_CLNT_3_DANGER_AGGR_CNTRL, 0x3),
  ICBCFG_HWIOI_DW(QM_CLNT_3_THROTTLE_LEVEL_QOS_n, 4, 0xEE000004),
  ICBCFG_HWIOI_DW(QM_CLNT_3_THROTTLE_LEVEL_QOS_n, 6, 0xEE000006),
  ICBCFG_HWIO_DW(QM_CLNT_3_THROTTLE_LEVEL_OUTPUT_EN, 0x1),

  /* SNOC/AgNoC */
  ICBCFG_HWIO_DW(QM_CLNT_4_DANGER_AGGR_CNTRL, 0x3),
  ICBCFG_HWIOI_DW(QM_CLNT_4_THROTTLE_LEVEL_QOS_n, 4, 0xEE000004),
  ICBCFG_HWIOI_DW(QM_CLNT_4_THROTTLE_LEVEL_QOS_n, 6, 0xEE000006),
  ICBCFG_HWIO_DW(QM_CLNT_4_THROTTLE_LEVEL_OUTPUT_EN, 0x1),

  /* AML1 */
  ICBCFG_HWIO_DW(QM_CLNT_5_DANGER_AGGR_CNTRL, 0x3),
  ICBCFG_HWIOI_DW(QM_CLNT_5_THROTTLE_LEVEL_QOS_n, 7, 0xEE000003),
  ICBCFG_HWIO_DW(QM_CLNT_5_THROTTLE_LEVEL_OUTPUT_EN, 0x3),

  /* IRIS VCodec/V-CPU */
  ICBCFG_HWIO_DW(QM_CLNT_6_DANGER_AGGR_CNTRL, 0x3),
  ICBCFG_HWIOI_DW(QM_CLNT_6_THROTTLE_LEVEL_QOS_n, 4, 0xEE000004),
  ICBCFG_HWIOI_DW(QM_CLNT_6_THROTTLE_LEVEL_QOS_n, 6, 0xEE000006),
  ICBCFG_HWIO_DW(QM_CLNT_6_THROTTLE_LEVEL_OUTPUT_EN, 0x1),

  /* IRIS CVP/CV-CPU */
  ICBCFG_HWIO_DW(QM_CLNT_7_DANGER_AGGR_CNTRL, 0x3),
  ICBCFG_HWIOI_DW(QM_CLNT_7_THROTTLE_LEVEL_QOS_n, 4, 0xEE000004),
  ICBCFG_HWIOI_DW(QM_CLNT_7_THROTTLE_LEVEL_QOS_n, 6, 0xEE000006),
  ICBCFG_HWIO_DW(QM_CLNT_7_THROTTLE_LEVEL_OUTPUT_EN, 0x1),

  /* GPU/GPUTCU */
  ICBCFG_HWIO_DW(QM_CLNT_8_DANGER_AGGR_CNTRL, 0x3),
  ICBCFG_HWIOI_DW(QM_CLNT_8_THROTTLE_LEVEL_QOS_n, 3, 0xEE000003),
  ICBCFG_HWIOI_DW(QM_CLNT_8_THROTTLE_LEVEL_QOS_n, 4, 0xEE000004),
  ICBCFG_HWIOI_DW(QM_CLNT_8_THROTTLE_LEVEL_QOS_n, 6, 0xEE000006),
  ICBCFG_HWIOI_DW(QM_CLNT_8_THROTTLE_LEVEL_QOS_n, 7, 0xAA000000),
  ICBCFG_HWIO_DW(QM_CLNT_8_THROTTLE_LEVEL_OUTPUT_EN, 0x3),

  /* CPU */
  ICBCFG_HWIO_DW(QM_CLNT_9_DANGER_AGGR_CNTRL, 0x3),
  ICBCFG_HWIOI_DW(QM_CLNT_9_THROTTLE_LEVEL_QOS_n, 3, 0xEE000003),
  ICBCFG_HWIOI_DW(QM_CLNT_9_THROTTLE_LEVEL_QOS_n, 4, 0xEE000004),
  ICBCFG_HWIOI_DW(QM_CLNT_9_THROTTLE_LEVEL_QOS_n, 6, 0xEE000006),
  ICBCFG_HWIOI_DW(QM_CLNT_9_THROTTLE_LEVEL_QOS_n, 7, 0xAA000000),
  ICBCFG_HWIO_DW(QM_CLNT_9_THROTTLE_LEVEL_OUTPUT_EN, 0x3),

  /* NSP/HCP/Audio-ML */
  ICBCFG_HWIO_DW(QM_DSP_DANGER_AGGR_CNTRL, 0x3),
  ICBCFG_HWIO_DW(QM_DSP_PRIORITY_MODE_SEL, 0x1),
  ICBCFG_HWIO_DW(QM_DSP_SYSTEM_DANGER_OUTPUT_EN, 0x1),
  ICBCFG_HWIOI_DW(QM_CLNT_10_THROTTLE_LEVEL_QOS_n, 3, 0xEE000003),
  ICBCFG_HWIOI_DW(QM_CLNT_10_THROTTLE_LEVEL_QOS_n, 4, 0xEE000004),
  ICBCFG_HWIOI_DW(QM_CLNT_10_THROTTLE_LEVEL_QOS_n, 6, 0xEE000006),
  ICBCFG_HWIOI_DW(QM_CLNT_10_THROTTLE_LEVEL_QOS_n, 7, 0xAA000000),
  ICBCFG_HWIO_DW(QM_CLNT_10_THROTTLE_LEVEL_OUTPUT_EN, 0x3),

  /* Throttle level generation */
  //ICBCFG_HWIO_DW(QM_THROTTLE_LEVEL_LEGACY_SELECT, 0x0),
  ICBCFG_HWIOI_DW(QM_THROTTLE_LEVEL_QOS_n, 7, 0x7FC),

  ICBCFG_HWIOF_READ_DW(MCCC_CLK_PERIOD,PERIOD),  // borrowed from kailua
  ICBCFG_HWIOF_WRITE_DW(QM_PERIOD_BUS_CFG,PERIOD_BUS_SW),  // borrowed from kailua
  ICBCFG_HWIOF_DW(QM_PERIOD_BUS_CFG, PERIOD_BUS_LOAD_SW, 0x1),  // borrowed from kailua
  ICBCFG_HWIOF_DW(QM_PERIOD_BUS_CFG, PERIOD_BUS_SW_OVERRIDE, 0x0),  // borrowed from kailua

  ICBCFG_HWIOI_DW(QOS_FREQ_BAND_BNDRY_n, 0, 0x97b),
  //ICBCFG_HWIO_DW(QM_DANGER_SAFE_CNTRL, 0x1), POR in Palawan

  /* AP throttles and shapers */
  //ICBCFG_HWIOF_DW(APP_BWMON_THROTTLE_0_CGC_CNTRL, THROTTLE_CGC_EN, 0x1),
  //ICBCFG_HWIOF_DW(APP_BWMON_THROTTLE_0_GRANT_PERIOD, GRANT_PERIOD, 0x3E8),
  //ICBCFG_HWIO_DW(APP_BWMON_THROTTLE_0_THRESHOLD_03, 0xFFFF),
  //ICBCFG_HWIO_DW(APP_BWMON_THROTTLE_0_THRESHOLD_02, 0xFFFF0032),
  //ICBCFG_HWIO_DW(APP_BWMON_THROTTLE_0_THRESHOLD_01, 0x0000FFFF),
  //ICBCFG_HWIO_DW(APP_BWMON_THROTTLE_0_THRESHOLD_00, 0x00000032),
  //ICBCFG_HWIOF_DW(APP_BWMON_THROTTLE_0_PEAK_ACCUM_CREDIT, PEAK_ACCUM_CREDIT, 0x100),
  ICBCFG_HWIO_DW(APP_BWMON_THROTTLE_0_CNTRL, 0xD801),

  //ICBCFG_HWIOF_DW(APP_BWMON_THROTTLE_1_CGC_CNTRL, THROTTLE_CGC_EN, 0x1),
  //ICBCFG_HWIOF_DW(APP_BWMON_THROTTLE_1_GRANT_PERIOD, GRANT_PERIOD, 0x3E8),
  //ICBCFG_HWIO_DW(APP_BWMON_THROTTLE_1_THRESHOLD_03, 0xFFFF),
  //ICBCFG_HWIO_DW(APP_BWMON_THROTTLE_1_THRESHOLD_02, 0xFFFF0032),
  //ICBCFG_HWIO_DW(APP_BWMON_THROTTLE_1_THRESHOLD_01, 0x0000FFFF),
  //ICBCFG_HWIO_DW(APP_BWMON_THROTTLE_1_THRESHOLD_00, 0x00000032),
  //ICBCFG_HWIOF_DW(APP_BWMON_THROTTLE_1_PEAK_ACCUM_CREDIT, PEAK_ACCUM_CREDIT, 0x100),
  ICBCFG_HWIO_DW(APP_BWMON_THROTTLE_1_CNTRL, 0xD801),

  /* GPU throttles and shapers */
  //ICBCFG_HWIOF_DW(GPU_BWMON_THROTTLE_0_CGC_CNTRL, THROTTLE_CGC_EN, 0x1),
  //ICBCFG_HWIOF_DW(GPU_BWMON_THROTTLE_0_GRANT_PERIOD, GRANT_PERIOD, 0x3E8),
  ICBCFG_HWIO_DW(GPU_BWMON_THROTTLE_0_THRESHOLD_00, 0x0000FFFF),
  //ICBCFG_HWIO_DW(GPU_BWMON_THROTTLE_0_THRESHOLD_01, 0x0000FFFF),
  //ICBCFG_HWIO_DW(GPU_BWMON_THROTTLE_0_THRESHOLD_02, 0xFFFF0032),
  //ICBCFG_HWIO_DW(GPU_BWMON_THROTTLE_0_THRESHOLD_03, 0xFFFF),
  //ICBCFG_HWIOF_DW(GPU_BWMON_THROTTLE_0_PEAK_ACCUM_CREDIT, PEAK_ACCUM_CREDIT, 0x100),
  ICBCFG_HWIO_DW(GPU_BWMON_THROTTLE_0_CNTRL, 0x5801),

  //ICBCFG_HWIOF_DW(GPU_BWMON_THROTTLE_1_CGC_CNTRL, THROTTLE_CGC_EN, 0x1),
  //ICBCFG_HWIOF_DW(GPU_BWMON_THROTTLE_1_GRANT_PERIOD, GRANT_PERIOD, 0x3E8),
  ICBCFG_HWIO_DW(GPU_BWMON_THROTTLE_1_THRESHOLD_00, 0x0000FFFF),
  //ICBCFG_HWIO_DW(GPU_BWMON_THROTTLE_1_THRESHOLD_01, 0x0000FFFF),
  //ICBCFG_HWIO_DW(GPU_BWMON_THROTTLE_1_THRESHOLD_02, 0xFFFF0032),
  //ICBCFG_HWIO_DW(GPU_BWMON_THROTTLE_1_THRESHOLD_03, 0xFFFF),
  //ICBCFG_HWIOF_DW(GPU_BWMON_THROTTLE_1_PEAK_ACCUM_CREDIT, PEAK_ACCUM_CREDIT, 0x100),
  ICBCFG_HWIO_DW(GPU_BWMON_THROTTLE_1_CNTRL, 0x5801),

  /* SNOC throttles and shapers */
  //ICBCFG_HWIO_DW(SNOC_THROTTLE_THROTTLE_0_CGC_CNTRL, 0x1),
  //ICBCFG_HWIO_DW(SNOC_THROTTLE_THROTTLE_0_GRANT_PERIOD, 0x3E8),
  ICBCFG_HWIO_DW(SNOC_THROTTLE_THROTTLE_0_THRESHOLD_00, 0x0000FFFF),
  //ICBCFG_HWIO_DW(SNOC_THROTTLE_THROTTLE_0_THRESHOLD_01, 0x0000FFFF),
  ICBCFG_HWIO_DW(SNOC_THROTTLE_THROTTLE_0_THRESHOLD_02, 0xFFFFFFFF),
  //ICBCFG_HWIO_DW(SNOC_THROTTLE_THROTTLE_0_PEAK_ACCUM_CREDIT, 0x100),
  ICBCFG_HWIO_DW(SNOC_THROTTLE_THROTTLE_0_CNTRL, 0x5001),

  /* A1NOC throttles and shapers */
  //ICBCFG_HWIO_DW(ANOC1_THROTTLE_THROTTLE_0_CGC_CNTRL, 0x1),
  //ICBCFG_HWIO_DW(ANOC1_THROTTLE_THROTTLE_0_GRANT_PERIOD, 0x3E8),
  ICBCFG_HWIO_DW(ANOC1_THROTTLE_THROTTLE_0_THRESHOLD_00, 0x0000FFFF),
  //ICBCFG_HWIO_DW(ANOC1_THROTTLE_THROTTLE_0_THRESHOLD_01, 0x0000FFFF),
  ICBCFG_HWIO_DW(ANOC1_THROTTLE_THROTTLE_0_THRESHOLD_02, 0xFFFFFFFF),
  //ICBCFG_HWIO_DW(ANOC1_THROTTLE_THROTTLE_0_PEAK_ACCUM_CREDIT, 0x100),
  ICBCFG_HWIO_DW(ANOC1_THROTTLE_THROTTLE_0_CNTRL, 0x5001),

  /* A2NOC throttles and shapers */
  ICBCFG_HWIO_DW(ANOC2_THROTTLE_THROTTLE_0_CNTRL, 0x5001),
  //ICBCFG_HWIO_DW(ANOC2_THROTTLE_THROTTLE_0_CGC_CNTRL, 0x1),
  //ICBCFG_HWIO_DW(ANOC2_THROTTLE_THROTTLE_0_GRANT_PERIOD, 0x3E8),
  ICBCFG_HWIO_DW(ANOC2_THROTTLE_THROTTLE_0_THRESHOLD_00, 0x0000FFFF),
  //ICBCFG_HWIO_DW(ANOC2_THROTTLE_THROTTLE_0_THRESHOLD_01, 0x0000FFFF),
  ICBCFG_HWIO_DW(ANOC2_THROTTLE_THROTTLE_0_THRESHOLD_02, 0xFFFFFFFF),
  //ICBCFG_HWIO_DW(ANOC2_THROTTLE_THROTTLE_0_PEAK_ACCUM_CREDIT, 0x100),

  /* LPASS_THROTTLE_THROTTLE_WRAPPER_1 */
  ICBCFG_HWIO_DW(LPASS_THROTTLE_THROTTLE_0_CNTRL, 0x5001),
  //ICBCFG_HWIO_DW(LPASS_THROTTLE_THROTTLE_0_CGC_CNTRL, 0x1),
  //ICBCFG_HWIO_DW(LPASS_THROTTLE_THROTTLE_0_GRANT_PERIOD, 0x3E8),
  ICBCFG_HWIO_DW(LPASS_THROTTLE_THROTTLE_0_THRESHOLD_00, 0x0000FFFF),
  //ICBCFG_HWIO_DW(LPASS_THROTTLE_THROTTLE_0_THRESHOLD_01, 0x0000FFFF),
  ICBCFG_HWIO_DW(LPASS_THROTTLE_THROTTLE_0_THRESHOLD_02, 0xFFFFFFFF),
  //ICBCFG_HWIO_DW(LPASS_THROTTLE_THROTTLE_0_PEAK_ACCUM_CREDIT, 0x100),

  /* GIC_THROTTLE_THROTTLE_0_THROTTLE_0_THROTTLE */
  //ICBCFG_HWIO_DW(GIC_THROTTLE_THROTTLE_0_CGC_CNTRL, 0x1),
  //ICBCFG_HWIO_DW(GIC_THROTTLE_THROTTLE_0_GRANT_PERIOD, 0x3E8),
  ICBCFG_HWIO_DW(GIC_THROTTLE_THROTTLE_0_THRESHOLD_00, 0x0000FFFF),
  //ICBCFG_HWIO_DW(GIC_THROTTLE_THROTTLE_0_THRESHOLD_01, 0x0000FFFF),
  ICBCFG_HWIO_DW(GIC_THROTTLE_THROTTLE_0_THRESHOLD_02, 0xFFFFFFFF),
  //ICBCFG_HWIO_DW(GIC_THROTTLE_THROTTLE_0_PEAK_ACCUM_CREDIT, 0x100),
  ICBCFG_HWIO_DW(GIC_THROTTLE_THROTTLE_0_CNTRL, 0x5001),

  /* WLAN_Q6_BWMON_THROTTLE_0_THROTTLE_0_THROTTLE */
  //ICBCFG_HWIO_DW(WLAN_Q6_THROTTLE_THROTTLE_0_THRESHOLD_00, 0x0000FFFF),
  //ICBCFG_HWIO_DW(WLAN_Q6_THROTTLE_THROTTLE_0_THRESHOLD_02, 0xFFFFFFFF),
  //ICBCFG_HWIO_DW(WLAN_Q6_THROTTLE_THROTTLE_0_CNTRL, 0x5001),
  
  /* CDSP_BWMON_THROTTLE_BWMON_WRAPPER_2 */
  //ICBCFG_HWIO_DW(CDSP_BWMON_THROTTLE_0_CGC_CNTRL, 0x1),
  //ICBCFG_HWIO_DW(CDSP_BWMON_THROTTLE_0_GRANT_PERIOD, 0x3E8),
  ICBCFG_HWIO_DW(CDSP_BWMON_THROTTLE_0_THRESHOLD_00, 0xFFFF),
  //ICBCFG_HWIO_DW(CDSP_BWMON_THROTTLE_0_THRESHOLD_01, 0xFFFF),
  //ICBCFG_HWIO_DW(CDSP_BWMON_THROTTLE_0_THRESHOLD_02, 0xFFFF0032),
  //ICBCFG_HWIO_DW(CDSP_BWMON_THROTTLE_0_THRESHOLD_03, 0xFFFF03E8),
  //ICBCFG_HWIO_DW(CDSP_BWMON_THROTTLE_0_PEAK_ACCUM_CREDIT, 0x100),
  ICBCFG_HWIO_DW(CDSP_BWMON_THROTTLE_0_CNTRL, 0x5801),

  //ICBCFG_HWIO_DW(CDSP_BWMON_THROTTLE_1_CGC_CNTRL, 0x1),
  //ICBCFG_HWIO_DW(CDSP_BWMON_THROTTLE_1_GRANT_PERIOD, 0x3E8),
  ICBCFG_HWIO_DW(CDSP_BWMON_THROTTLE_1_THRESHOLD_00, 0xFFFF),
  //ICBCFG_HWIO_DW(CDSP_BWMON_THROTTLE_1_THRESHOLD_01, 0xFFFF),
  //ICBCFG_HWIO_DW(CDSP_BWMON_THROTTLE_1_THRESHOLD_02, 0xFFFF0032),
  //ICBCFG_HWIO_DW(CDSP_BWMON_THROTTLE_1_THRESHOLD_03, 0xFFFF03E8),
  //ICBCFG_HWIO_DW(CDSP_BWMON_THROTTLE_1_PEAK_ACCUM_CREDIT, 0x100),
  ICBCFG_HWIO_DW(CDSP_BWMON_THROTTLE_1_CNTRL, 0x5801),

};

icbcfg_prop_seg_type icbcfg_qm_cfg_seg_palawan_v1 = 
{
  /* Length of the config  data array */
  ARRAY_SIZE(icbcfg_qm_cfg_data_palawan_v1),
  /* Pointer to config data array */ 
  icbcfg_qm_cfg_data_palawan_v1                                    
};

/*---------------------------------------------------------------------------*/
/* GEMNOC Early Config Segment                                               */
/*---------------------------------------------------------------------------*/
icbcfg_data_type icbcfg_gemnoc_early_cfg_data_palawan_v1[] =
{
  ICBCFG_HWIO_DW(GEM_NOC_FORCE_CLKON_CSRUNIT_RCG_APSS_GIC_CLK_FORCECLKON_LOW, 0x1),
  ICBCFG_HWIO_DW(GEM_NOC_FORCE_CLKON_CSRUNIT_RCG_CNOC_SF_CLK_FORCECLKON_LOW, 0x1),
  ICBCFG_HWIO_DW(GEM_NOC_FORCE_CLKON_CSRUNIT_RCG_GEMNOC_CFG_CLK_FORCECLKON_LOW, 0x1),
  ICBCFG_HWIO_DW(GEM_NOC_FORCE_CLKON_CSRUNIT_RCG_GEMNOC_CLK_FORCECLKON_LOW, 0x1),
  ICBCFG_HWIO_DW(GEM_NOC_FORCE_CLKON_CSRUNIT_RCG_GPU_CLK_FORCECLKON_LOW, 0x1),
  ICBCFG_HWIO_DW(GEM_NOC_FORCE_CLKON_CSRUNIT_RCG_LPASS_CLK_FORCECLKON_LOW, 0x1),
  ICBCFG_HWIO_DW(GEM_NOC_FORCE_CLKON_CSRUNIT_RCG_MNOC_HF_CLK_FORCECLKON_LOW, 0x1),
  ICBCFG_HWIO_DW(GEM_NOC_FORCE_CLKON_CSRUNIT_RCG_MNOC_SF_CLK_FORCECLKON_LOW, 0x1),
  ICBCFG_HWIO_DW(GEM_NOC_FORCE_CLKON_CSRUNIT_RCG_MODEM_CLK_FORCECLKON_LOW, 0x1),
  ICBCFG_HWIO_DW(GEM_NOC_FORCE_CLKON_CSRUNIT_RCG_NSP_NOC_CLK_FORCECLKON_LOW, 0x1),
  ICBCFG_HWIO_DW(GEM_NOC_FORCE_CLKON_CSRUNIT_RCG_PCIE_SF_CLK_FORCECLKON_LOW, 0x1),
  ICBCFG_HWIO_DW(GEM_NOC_FORCE_CLKON_CSRUNIT_RCG_PWRCTL_CLK_FORCECLKON_LOW, 0x1),
  ICBCFG_HWIO_DW(GEM_NOC_FORCE_CLKON_CSRUNIT_RCG_SNOC_SF_CLK_FORCECLKON_LOW, 0x1),
  ICBCFG_HWIO_DW(GEM_NOC_FORCE_CLKON_CSRUNIT_RCG_SYS_TCU_CLK_FORCECLKON_LOW, 0x1),
  ICBCFG_HWIO_DW(GEM_NOC_FORCE_CLKON_CSRUNIT_RCG_WLAN_Q6_CLK_FORCECLKON_LOW, 0x1),

  ICBCFG_HWIO_DW(GEM_NOC_CNOC_SF_CLK_RCGCONTROLLER_HYSTERESIS_LOW, 0x3FF),
  ICBCFG_HWIO_DW(GEM_NOC_GEMNOC_CFG_CLK_RCGCONTROLLER_HYSTERESIS_LOW, 0x3FF),
  ICBCFG_HWIO_DW(GEM_NOC_GEMNOC_CLK_RCGCONTROLLER_HYSTERESIS_LOW, 0x3FF),
  ICBCFG_HWIO_DW(GEM_NOC_GPU_CLK_RCGCONTROLLER_HYSTERESIS_LOW, 0x3FF),
  ICBCFG_HWIO_DW(GEM_NOC_LPASS_CLK_RCGCONTROLLER_HYSTERESIS_LOW, 0x3FF),
  ICBCFG_HWIO_DW(GEM_NOC_MNOC_HF_CLK_RCGCONTROLLER_HYSTERESIS_LOW, 0x3FF),
  ICBCFG_HWIO_DW(GEM_NOC_MNOC_SF_CLK_RCGCONTROLLER_HYSTERESIS_LOW, 0x3FF),
  ICBCFG_HWIO_DW(GEM_NOC_MODEM_CLK_RCGCONTROLLER_HYSTERESIS_LOW, 0x3FF),
  ICBCFG_HWIO_DW(GEM_NOC_NSP_NOC_CLK_RCGCONTROLLER_HYSTERESIS_LOW, 0x3FF),
  ICBCFG_HWIO_DW(GEM_NOC_PCIE_SF_CLK_RCGCONTROLLER_HYSTERESIS_LOW, 0x3FF),
  ICBCFG_HWIO_DW(GEM_NOC_APSS_GIC_CLK_RCGCONTROLLER_HYSTERESIS_LOW, 0x3FF),
  ICBCFG_HWIO_DW(GEM_NOC_SNOC_SF_CLK_RCGCONTROLLER_HYSTERESIS_LOW, 0x3FF),
  ICBCFG_HWIO_DW(GEM_NOC_SYS_TCU_CLK_RCGCONTROLLER_HYSTERESIS_LOW, 0x3FF),
  ICBCFG_HWIO_DW(GEM_NOC_WLAN_Q6_CLK_RCGCONTROLLER_HYSTERESIS_LOW, 0x3FF),

  ICBCFG_HWIO_DW(GEM_NOC_FORCE_CLKON_CSRUNIT_RCG_APSS_GIC_CLK_ENABLE_LOW, 0x1),
  ICBCFG_HWIO_DW(GEM_NOC_FORCE_CLKON_CSRUNIT_RCG_CNOC_SF_CLK_ENABLE_LOW, 0x1),
  ICBCFG_HWIO_DW(GEM_NOC_FORCE_CLKON_CSRUNIT_RCG_GEMNOC_CFG_CLK_ACTIVEDIS_LOW, 0x1),
  ICBCFG_HWIO_DW(GEM_NOC_FORCE_CLKON_CSRUNIT_RCG_GEMNOC_CFG_CLK_ENABLE_LOW, 0x1),
  ICBCFG_HWIO_DW(GEM_NOC_FORCE_CLKON_CSRUNIT_RCG_GEMNOC_CLK_ENABLE_LOW, 0x1),
  ICBCFG_HWIO_DW(GEM_NOC_FORCE_CLKON_CSRUNIT_RCG_GPU_CLK_ENABLE_LOW, 0x1),
  ICBCFG_HWIO_DW(GEM_NOC_FORCE_CLKON_CSRUNIT_RCG_LPASS_CLK_ENABLE_LOW, 0x1),
  ICBCFG_HWIO_DW(GEM_NOC_FORCE_CLKON_CSRUNIT_RCG_MNOC_HF_CLK_ENABLE_LOW, 0x1),
  ICBCFG_HWIO_DW(GEM_NOC_FORCE_CLKON_CSRUNIT_RCG_MNOC_SF_CLK_ENABLE_LOW, 0x1),
  ICBCFG_HWIO_DW(GEM_NOC_FORCE_CLKON_CSRUNIT_RCG_MODEM_CLK_ENABLE_LOW, 0x1),
  ICBCFG_HWIO_DW(GEM_NOC_FORCE_CLKON_CSRUNIT_RCG_NSP_NOC_CLK_ENABLE_LOW, 0x1),
  ICBCFG_HWIO_DW(GEM_NOC_FORCE_CLKON_CSRUNIT_RCG_PCIE_SF_CLK_ENABLE_LOW, 0x1),
  ICBCFG_HWIO_DW(GEM_NOC_FORCE_CLKON_CSRUNIT_RCG_SNOC_SF_CLK_ENABLE_LOW, 0x1),
  ICBCFG_HWIO_DW(GEM_NOC_FORCE_CLKON_CSRUNIT_RCG_SYS_TCU_CLK_ENABLE_LOW, 0x1),
  ICBCFG_HWIO_DW(GEM_NOC_FORCE_CLKON_CSRUNIT_RCG_WLAN_Q6_CLK_ENABLE_LOW, 0x1),

  ICBCFG_HWIO_DW(GEM_NOC_FORCE_CLKON_CSRUNIT_RCG_APSS_GIC_CLK_FORCECLKON_LOW, 0x0),
  ICBCFG_HWIO_DW(GEM_NOC_FORCE_CLKON_CSRUNIT_RCG_CNOC_SF_CLK_FORCECLKON_LOW, 0x0),
  ICBCFG_HWIO_DW(GEM_NOC_FORCE_CLKON_CSRUNIT_RCG_GEMNOC_CFG_CLK_FORCECLKON_LOW, 0x0),
  ICBCFG_HWIO_DW(GEM_NOC_FORCE_CLKON_CSRUNIT_RCG_GEMNOC_CLK_FORCECLKON_LOW, 0x0),
  ICBCFG_HWIO_DW(GEM_NOC_FORCE_CLKON_CSRUNIT_RCG_GPU_CLK_FORCECLKON_LOW, 0x0),
  ICBCFG_HWIO_DW(GEM_NOC_FORCE_CLKON_CSRUNIT_RCG_LPASS_CLK_FORCECLKON_LOW, 0x0),
  ICBCFG_HWIO_DW(GEM_NOC_FORCE_CLKON_CSRUNIT_RCG_MNOC_HF_CLK_FORCECLKON_LOW, 0x0),
  ICBCFG_HWIO_DW(GEM_NOC_FORCE_CLKON_CSRUNIT_RCG_MNOC_SF_CLK_FORCECLKON_LOW, 0x0),
  ICBCFG_HWIO_DW(GEM_NOC_FORCE_CLKON_CSRUNIT_RCG_MODEM_CLK_FORCECLKON_LOW, 0x0),
  ICBCFG_HWIO_DW(GEM_NOC_FORCE_CLKON_CSRUNIT_RCG_NSP_NOC_CLK_FORCECLKON_LOW, 0x0),
  ICBCFG_HWIO_DW(GEM_NOC_FORCE_CLKON_CSRUNIT_RCG_PCIE_SF_CLK_FORCECLKON_LOW, 0x0),
  ICBCFG_HWIO_DW(GEM_NOC_FORCE_CLKON_CSRUNIT_RCG_PWRCTL_CLK_FORCECLKON_LOW, 0x0),
  ICBCFG_HWIO_DW(GEM_NOC_FORCE_CLKON_CSRUNIT_RCG_SNOC_SF_CLK_FORCECLKON_LOW, 0x0),
  ICBCFG_HWIO_DW(GEM_NOC_FORCE_CLKON_CSRUNIT_RCG_SYS_TCU_CLK_FORCECLKON_LOW, 0x0),
  ICBCFG_HWIO_DW(GEM_NOC_FORCE_CLKON_CSRUNIT_RCG_WLAN_Q6_CLK_FORCECLKON_LOW, 0x0),

  /* SCID overrides - This change is Moved to TME due to AC constrians*/
  // ICBCFG_HWIO_DW(GEM_NOC_ALM_GPU_TCU_DYNATTR_CACHEINDEXVAL_LOW, 0x0000000B),
  // ICBCFG_HWIO_DW(GEM_NOC_ALM_GPU_TCU_DYNATTR_MAINCTL_LOW, 0x00100000),
  // ICBCFG_HWIO_DW(GEM_NOC_ALM_SYS_TCU_DYNATTR_CACHEINDEXVAL_LOW, 0x00000012),
  // ICBCFG_HWIO_DW(GEM_NOC_ALM_SYS_TCU_DYNATTR_MAINCTL_LOW, 0x00100000),

  /* Other HSR */
  ICBCFG_HWIO_DW(GEM_NOC_QCIDIRECTORY_EVEN_SNOOPFILTER_QNS_LLCC0_CTL_MAINCTL_LOW, 0x00000004),
  ICBCFG_HWIO_DW(GEM_NOC_QCIDIRECTORY_EVEN_SNOOPFILTER_QNS_LLCC2_CTL_MAINCTL_LOW, 0x00000004),
  ICBCFG_HWIO_DW(GEM_NOC_QCIDIRECTORY_ODD_SNOOPFILTER_QNS_LLCC1_CTL_MAINCTL_LOW, 0x00000004),
  ICBCFG_HWIO_DW(GEM_NOC_QCIDIRECTORY_ODD_SNOOPFILTER_QNS_LLCC3_CTL_MAINCTL_LOW, 0x00000004),

  ICBCFG_HWIO_DW(GEM_NOC_QNS_LLCC0_POC_DBG_CFG_LOW, 0x00020000),
  ICBCFG_HWIO_DW(GEM_NOC_QNS_LLCC1_POC_DBG_CFG_LOW, 0x00020000),
  ICBCFG_HWIO_DW(GEM_NOC_QNS_LLCC2_POC_DBG_CFG_LOW, 0x00020000),
  ICBCFG_HWIO_DW(GEM_NOC_QNS_LLCC3_POC_DBG_CFG_LOW, 0x00020000),
};

icbcfg_prop_seg_type icbcfg_gemnoc_early_cfg_seg_palawan_v1 = 
{
  /* Length of the config  data array */
  ARRAY_SIZE(icbcfg_gemnoc_early_cfg_data_palawan_v1),
  /* Pointer to config data array */ 
  icbcfg_gemnoc_early_cfg_data_palawan_v1                                    
};

/*---------------------------------------------------------------------------*/
/* Init Config Segment list                                                  */
/*---------------------------------------------------------------------------*/
icbcfg_prop_seg_type *icbcfg_boot_segs_palawan_v1[] =
{
  &icbcfg_qm_cfg_seg_palawan_v1,
  &icbcfg_gemnoc_early_cfg_seg_palawan_v1,
};

icbcfg_prop_type icbcfg_boot_prop_palawan_v1 =
{
  /* Length of the config  data array */
  ARRAY_SIZE(icbcfg_boot_segs_palawan_v1),
  /* Pointer to config data array */
  icbcfg_boot_segs_palawan_v1
};

/*---------------------------------------------------------------------------*/
/* PostInit Config Segments                                                  */
/*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*/
/* GEMNOC Post Config Segment                                                */
/*---------------------------------------------------------------------------*/
icbcfg_data_type icbcfg_gemnoc_cfg_data_palawan_v1[] =
{
  ICBCFG_DEFAULT(),
};

icbcfg_prop_seg_type icbcfg_gemnoc_cfg_seg_palawan_v1 =
{
  /* Length of the config  data array */
  ARRAY_SIZE(icbcfg_gemnoc_cfg_data_palawan_v1),
  /* Pointer to config data array */
  icbcfg_gemnoc_cfg_data_palawan_v1
};

/*---------------------------------------------------------------------------*/
/* LLCC Config Segment                                                       */
/*---------------------------------------------------------------------------*/
icbcfg_data_type icbcfg_llcc_cfg_data_palawan_v1[] =
{
  /* TCM config */
  ICBCFG_HWIO_DW(LLCC_BROADCAST_ORLLCC_FEAC_TCM0_MASK_CFG, 0x00001F80),
  ICBCFG_HWIO_DW(LLCC_BROADCAST_ORLLCC_FEAC_TCM_ADDR_BASE_CFG, 0x00800070),
  ICBCFG_HWIO_DW(LLCC_BROADCAST_ORLLCC_FEAC_VICTIM_ZONE2_CFG0, 0xFF004500),
  ICBCFG_HWIO_DW(LLCC_BROADCAST_ORLLCC_FEAC_VICTIM_ZONE2_CFG1, 0x000000F3),
  ICBCFG_HWIO_DW(LLCC_BROADCAST_ORLLCC_FEAC_VICTIM_ZONE3_CFG0, 0xFE006000),
  ICBCFG_HWIO_DW(LLCC_BROADCAST_ORLLCC_FEAC_VICTIM_ZONE3_CFG1, 0x000000F3),
  ICBCFG_HWIO_DW(LLCC_BROADCAST_ORLLCC_FEAC_VICTIM_ZONE4_CFG0, 0xFF00E000),
  ICBCFG_HWIO_DW(LLCC_BROADCAST_ORLLCC_FEAC_VICTIM_ZONE4_CFG1, 0x000000F3),

  /* TRP algo */
  ICBCFG_HWIO_DW(LLCC_BROADCAST_ORLLCC_TRP_ALGO_CFG0, 0x00100000),
  ICBCFG_HWIO_DW(LLCC_BROADCAST_ORLLCC_TRP_ALGO_CFG5, 0x40000000),
  ICBCFG_HWIOI_DW(LLCC_BROADCAST_ORLLCC_TRP_SCT_n_ATTRIBUTE1_CFG, 30, 0x02000038),
  ICBCFG_HWIOI_DW(LLCC_BROADCAST_ORLLCC_TRP_SCT_n_ATTRIBUTE2_CFG, 30, 0x00003FFF),

  /* SCID overrides */
  ICBCFG_HWIO_DW(LLCC_BROADCAST_ORLLCC_TRP_RD_NOALLOC_ON_MISS_OVERRIDE_CFG0, 0x40440800),
  ICBCFG_HWIO_DW(LLCC_BROADCAST_ORLLCC_TRP_RWE_OVERRIDE_CFG0, 0x00000020),

  /* Island Overrides */
  ICBCFG_HWIO_DW(LLCC_BROADCAST_ORLLCC_LPI_SHARED_ISLAND_UIMAGE_CFG, 0x000E0FF8),
  ICBCFG_HWIOI_DW(LLCC_BROADCAST_ORLLCC_LPI_SHARED_SCT_n_TYPE_CFG, 1, 0x00000001),
  ICBCFG_HWIOI_DW(LLCC_BROADCAST_ORLLCC_LPI_SHARED_SCT_n_TYPE_CFG, 12, 0x00000003),
  ICBCFG_HWIOI_DW(LLCC_BROADCAST_ORLLCC_LPI_SHARED_SCT_n_TYPE_CFG, 18, 0x00000001),
  ICBCFG_HWIOI_DW(LLCC_BROADCAST_ORLLCC_LPI_SHARED_SCT_n_TYPE_CFG, 27, 0x00000001),
  ICBCFG_HWIOI_DW(LLCC_BROADCAST_ORLLCC_LPI_SHARED_SCT_n_TYPE_CFG, 29, 0x00000001),
  ICBCFG_HWIOI_DW(LLCC_BROADCAST_ORLLCC_LPI_SHARED_SCT_n_TYPE_CFG, 30, 0x00000001),
  ICBCFG_HWIOI_DW(LLCC_BROADCAST_ORLLCC_LPI_SHARED_SCT_n_TYPE_CFG, 31, 0x00000001),

  /* LLCC TAG sequence */
  ICBCFG_HWIO_DW(LLCC_BROADCAST_ORLLCC_TRP_NC_AS_C_OVERRIDE_CFG, 0xFFFFFFFF),
  ICBCFG_HWIO_DW(LLCC_BROADCAST_ANDLLCC_TRP_C_AS_NC_OVERRIDE_CFG, 0x00000000),
};

icbcfg_prop_seg_type icbcfg_llcc_cfg_seg_palawan_v1 =
{
  /* Length of the config  data array */
  ARRAY_SIZE(icbcfg_llcc_cfg_data_palawan_v1),
  /* Pointer to config data array */
  icbcfg_llcc_cfg_data_palawan_v1
};

/*---------------------------------------------------------------------------*/
/* LLCC Config Segment                                                       */
/*---------------------------------------------------------------------------*/
icbcfg_data_type icbcfg_wa_data_palawan_v1[] =
{
  /* CNOC HSR settings */
  ICBCFG_HWIO_DW(CNOC_MAIN_CSRUNIT_MAIN_MEMTYPE_CSRUNIT_QHB_MEMTYPE_QHS_AOSS_LOW, 0x00000002),
  ICBCFG_HWIO_DW(CNOC_MAIN_CSRUNIT_MAIN_MEMTYPE_CSRUNIT_QHB_MEMTYPE_QHS_IPA_LOW, 0x00000002),
  ICBCFG_HWIO_DW(CNOC_MAIN_CSRUNIT_MAIN_MEMTYPE_CSRUNIT_QHB_MEMTYPE_QHS_IPC_ROUTER_LOW, 0x00000002),
  
  /* DC_NOC RCG settings */
  ICBCFG_HWIO_DW(DC_NOC_DCH_CSRUNIT_RCG_CSRUNIT_RCG_DC_NOC_CLK_DCH_FORCECLKON_LOW, 0x1),
  ICBCFG_HWIO_DW(DC_NOC_CH02_SERVICE_NETWORKDC_NOC_CH_HM_CSRUNIT_RCG_DC_NOC_CLK_CH_HM_FORCECLKON_LOW, 0x1),
  ICBCFG_HWIO_DW(DC_NOC_CH13_SERVICE_NETWORKDC_NOC_CH_HM_CSRUNIT_RCG_DC_NOC_CLK_CH_HM_FORCECLKON_LOW, 0x1),
  
  ICBCFG_HWIO_DW(DC_NOC_DCH_DC_NOC_CLK_DCH_RCGCONTROLLER_HYSTERESIS_LOW, 0x3FF),
  ICBCFG_HWIO_DW(DC_NOC_CH02_SERVICE_NETWORKDC_NOC_CH_HM_DC_NOC_CLK_CH_HM_RCGCONTROLLER_HYSTERESIS_LOW, 0x3FF),
  ICBCFG_HWIO_DW(DC_NOC_CH13_SERVICE_NETWORKDC_NOC_CH_HM_DC_NOC_CLK_CH_HM_RCGCONTROLLER_HYSTERESIS_LOW, 0x3FF),
  
  ICBCFG_HWIO_DW(DC_NOC_DCH_DC_NOC_CLK_DCH_RCGCONTROLLER_WAKEUP_LOW, 0x8),
  ICBCFG_HWIO_DW(DC_NOC_CH02_SERVICE_NETWORKDC_NOC_CH_HM_DC_NOC_CLK_CH_HM_RCGCONTROLLER_WAKEUP_LOW, 0x8),
  ICBCFG_HWIO_DW(DC_NOC_CH13_SERVICE_NETWORKDC_NOC_CH_HM_DC_NOC_CLK_CH_HM_RCGCONTROLLER_WAKEUP_LOW, 0x8),
  
  ICBCFG_HWIO_DW(DC_NOC_DCH_CSRUNIT_RCG_CSRUNIT_RCG_DC_NOC_CLK_DCH_ENABLE_LOW, 0x1),
  ICBCFG_HWIO_DW(DC_NOC_CH02_SERVICE_NETWORKDC_NOC_CH_HM_CSRUNIT_RCG_DC_NOC_CLK_CH_HM_ENABLE_LOW, 0x1),
  ICBCFG_HWIO_DW(DC_NOC_CH13_SERVICE_NETWORKDC_NOC_CH_HM_CSRUNIT_RCG_DC_NOC_CLK_CH_HM_ENABLE_LOW, 0x1),
  
  ICBCFG_HWIO_DW(DC_NOC_DCH_CSRUNIT_RCG_CSRUNIT_RCG_DC_NOC_CLK_DCH_FORCECLKON_LOW, 0x0),
  ICBCFG_HWIO_DW(DC_NOC_CH02_SERVICE_NETWORKDC_NOC_CH_HM_CSRUNIT_RCG_DC_NOC_CLK_CH_HM_FORCECLKON_LOW, 0x0),
  ICBCFG_HWIO_DW(DC_NOC_CH13_SERVICE_NETWORKDC_NOC_CH_HM_CSRUNIT_RCG_DC_NOC_CLK_CH_HM_FORCECLKON_LOW, 0x0),

};

icbcfg_prop_seg_type icbcfg_wa_seg_palawan_v1 =
{
  /* Length of the config  data array */
  ARRAY_SIZE(icbcfg_wa_data_palawan_v1),
  /* Pointer to config data array */
  icbcfg_wa_data_palawan_v1
};

/*---------------------------------------------------------------------------*/
/* PostInit Config Segment list                                              */
/*---------------------------------------------------------------------------*/
icbcfg_prop_seg_type *icbcfg_post_boot_segs_palawan_v1[] =
{
  &icbcfg_gemnoc_cfg_seg_palawan_v1,
  &icbcfg_llcc_cfg_seg_palawan_v1,
  &icbcfg_wa_seg_palawan_v1,
};

icbcfg_prop_type icbcfg_post_prop_palawan_v1 =
{
  /* Length of the config  data array */
  ARRAY_SIZE(icbcfg_post_boot_segs_palawan_v1),
  /* Pointer to config data array */
  icbcfg_post_boot_segs_palawan_v1
};

icbcfg_mem_region_type map_ddr_regions_palawan_v1[] =
{
  { 0x0080000000ULL, 0x0100000000ULL },
  { 0x0880000000ULL, 0x1000000000ULL },
};

/* Translation block base addresses. */
uint8 *trans_bases_palawan_v1[] =
{
  (uint8 *)HWIO_ADDR(LLCC0_LLCC_BEAC0_LLCC_BEAC_ADDR_TRANSLATOR_CFG),
  (uint8 *)HWIO_ADDR(LLCC1_LLCC_BEAC0_LLCC_BEAC_ADDR_TRANSLATOR_CFG),
  (uint8 *)HWIO_ADDR(LLCC2_LLCC_BEAC0_LLCC_BEAC_ADDR_TRANSLATOR_CFG),
  (uint8 *)HWIO_ADDR(LLCC3_LLCC_BEAC0_LLCC_BEAC_ADDR_TRANSLATOR_CFG),
};

icbcfg_device_config_type palawan_v1 =
{
  /* Chip version information for this device data. */
  CHIPINFO_FAMILY_PALAWAN,      /**< Chip family */
  false,                       /**< Exact match for version? */
  0,                           /**< Chip version */

  /* Device information. */
  ARRAY_SIZE(map_ddr_regions_palawan_v1), /**< Number of regions in the DDR map */
  map_ddr_regions_palawan_v1,             /**< Array of mappable DDR regions */
  6,                                     /**< Number of mapping segments. */
  4,                                     /**< Number of channels. */
  36,                                    /**< Address width in bits. */
  ICBCFG_ADDR_TRANS_LLCC,                /**< Address translator hardware type. */
  trans_bases_palawan_v1,                 /**< Translation block base addresses. */

  /* Prop lists. */
  &icbcfg_boot_prop_palawan_v1,           /**< Init time prop list. */
  &icbcfg_post_prop_palawan_v1,           /**< Post-init time prop list. */
};

/*---------------------------------------------------------------------------*/
/* TARGET LIST                                                               */
/*---------------------------------------------------------------------------*/
icbcfg_device_config_type *configs_palawan[] =
{
  &palawan_v1,
};

/*---------------------------------------------------------------------------*/
/* EXPORTED TARGET DEFINITION                                                */
/*---------------------------------------------------------------------------*/
icbcfg_info_type icbcfg_info =
{
  ARRAY_SIZE(configs_palawan),
  configs_palawan,
};
